config/routes.rb
Tasker::Application.routes.draw do

  resources :lists do
    resources :tasks
  end

  get "mocks/home"
  get "mocks/edit"

  root :to => 'lists#index'

  match '/login' => 'sessions#new', :as => 'login'

  match '/auth/twitter/callback' => 'sessions#create'
  match '/auth/failure' => 'sessions#failure'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :order, :user_id

  has_many :tasks
  belongs_to :user

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :complete, :description, :list_id, :notes, :position

  scope :ordered, order("position ASC, updated_at DESC")

  belongs_to :list

  before_create :init_position
  after_update :reposition_tasks

  private

  def init_position
    if list
      self.position = list.tasks.count
    end
  end

  def reposition_tasks
    if list.tasks.reload.where("position = #{position} AND id != #{id}").count > 0
      Task.transaction do
        list.tasks.ordered.each_with_index do |task, index|
          unless task.position == index
            task.update_attribute(:position, index)
          end
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :image_url, :name, :screen_name, :uid

  has_many :lists
  has_many :tasks, :through => :lists

  def self.create_from_auth_hash(auth)
    create! do |user|
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.screen_name = auth['info']['nickname'] || ""
         user.image_url = auth['info']['image'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    return nil unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end
  helper_method :current_user

  def require_user
    redirect_to login_url unless session[:user_id]
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_filter :require_user

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists.all
    @list = @lists.first

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = current_user.lists.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = current_user.lists.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = current_user.lists.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = current_user.lists.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = current_user.lists.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/mocks_controller.rb
class MocksController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :text => "<a class=\"btn btn-info\" href='/auth/twitter'>Login via Twitter</a>", :layout => true
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:uid => auth['uid'].to_s).first || User.create_from_auth_hash(auth)
    session[:user_id] = user.id
    redirect_to :root
  end

  def failure
    render :text => "FAILURE :-("
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :require_user
  before_filter :find_list

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @list.tasks.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = @list.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = @list.tasks.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = @list.tasks.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @list.tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @list, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: [@list, @task] }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = @list.tasks.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @list, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = @list.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to @list }
      format.json { head :no_content }
    end
  end

  private

  def find_list
    @list = current_user.lists.find(params[:list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tasker" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Tasker</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to 'New List', new_list_path, :class => "new_list" %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" style="margin-top:50px">
        <div class="row">
          <div class="span12">
            <% bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Tasker <%= Time.now.year %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/_nav.html.erb
<ul class="nav nav-pills nav-stacked">
  <% current_user.lists.each_with_index do |list, index| %>
    <li class="<%= @list == list ? "active" : "" %>">
      <%= link_to list.name, list %>
    </li>
  <% end %>
  <li id="new_list" class="hidden">
    <icon data-rel="new_list" class="icon-remove-circle pull-right"></icon>
    <%= form_for List.new do |f| %>
      <%= f.text_field :name, :placeholder => "New list name" %>
    <% end %>
  </li>
</ul>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<div class="row">
  <div class="span2"></div>
  <div class="span2">
    <ul class="nav nav-pills nav-stacked">
      <% @lists.each_with_index do |list, index| %>
        <% if index == 0 %>
          <li class="active"><%= link_to list.name, list %></li>
        <% else %>
          <li><%= link_to list.name, list %></li>
        <% end %>
      <% end %>
      <li id="new_list" class="hidden">
        <icon data-rel="new_list" class="icon-remove-circle pull-right"></icon>
        <%= form_for List.new do |f| %>
          <%= f.text_field :name, :placeholder => "New list name" %>
        <% end %>
      </li>
    </ul>
  </div>
  <div class="span5">
    <ul class="tasklist">
      <li>
        <input type="text" placeholder="What do you have to do?">
      </li>
      <li>
        <input type="checkbox" class="pull-left">
        <div class="content">
          <div class="actions pull-right">
            <i class="icon-pencil"></i>
            <i class="icon-move"></i>
          </div>
          <span>two</span>
          <div class="notes">
            <hr>
            <p>These are some notes.</p>
          </div>
        </div>
      </li>
      <li>
        <input type="checkbox" class="pull-left">
        <div class="content">
          <div class="actions pull-right">
            <i class="icon-pencil"></i>
            <i class="icon-move"></i>
          </div>
          <span>three</span>
        </div>
      </li>
    </ul>
  </div>
  <div class="span3"></div>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<div class="row">
  <div class="span2"></div>
  <div class="span2">
    <%= render :partial => "nav" %>
  </div>
  <div class="span5">
    <ul class="tasklist">
      <li id="new_task">
        <%= form_for [@list, Task.new] do |f| %>
          <%= f.text_field :description, :placeholder => "What do you have to do?" %>
        <% end %>
      </li>
      <%= render @list.tasks.ordered %>
    </ul>
  </div>
  <div class="span3"></div>
</div>

app/views/mocks/edit.html.erb
<div class="row">
  <div class="span2"></div>
  <div class="span2">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><a href="">Home</a></li>
      <li><a href="">Work</a></li>
    </ul>
  </div>
  <div class="span5">
    <div class="tab-content">
      <ul class="tasklist">
        <li>
          <input type="text" placeholder="What do you have to do?">
        </li>
        <li class="edit">
          <input type="checkbox" class="pull-left">
          <div class="content">
            <input type="text" value="two">
            <div class="notes">
              <hr>
              <textarea>These are some notes.</textarea>
            </div>
            <div class="buttons">
              <button class="btn btn-mini" type="button">Cancel</button>
              <button class="btn-primary btn btn-mini" type="button">Save</button>
            </div>
          </div>
        </li>
        <li>
          <label class="checkbox"><input type="checkbox">three</label>
        </li>
      </ul>
    </div>
  </div>
  <div class="span3"></div>
</div>

app/views/mocks/home.html.erb
<div class="row">
  <div class="span2"></div>
  <div class="span2">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><a href="">Home</a></li>
      <li><a href="">Work</a></li>
    </ul>
  </div>
  <div class="span5">
    <div class="tab-content">
      <ul class="tasklist">
        <li>
          <input type="text" placeholder="What do you have to do?">
        </li>
        <li>
          <input type="checkbox" class="pull-left">
          <div class="content">
            <div class="actions pull-right">
              <i class="icon-pencil"></i>
              <i class="icon-move"></i>
            </div>
            <span>two</span>
            <div class="notes">
              <hr>
              <p>These are some notes.</p>
            </div>
          </div>
        </li>
        <li>
          <input type="checkbox" class="pull-left">
          <div class="content">
            <div class="actions pull-right">
              <i class="icon-pencil"></i>
              <i class="icon-move"></i>
            </div>
            <span>three</span>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <div class="span3"></div>
</div>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_id %><br />
    <%= f.number_field :list_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :complete %><br />
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li id="task_<%= task.id %>" data-id="<%= task.id %>" data-rel="<%= url_for([task.list, task]) %>" class="task collapsed">
  <% if task.complete? %>
    <icon class="icon-check pull-left"></icon>
  <% else %>
    <input type="checkbox" class="checkbox pull-left" rel="edit_task_<%= task.id %>" <%= task.complete? ? "checked=\"checked\"" : "" %>>
  <% end %>
  <%= form_for [@list, task] do |f| %>
    <%= f.check_box :complete, :class => "hidden_checkbox hidden" %>
    <%= f.text_field :description, :class => "focus" %>
    <div class="">
      <hr>
      <%= f.text_area :notes, :cols => "", :rows => "" %>
    </div>
    <div class="buttons">
      <%= link_to 'Destroy', [@list, task], :class => "delete", :method => :delete, :data => { confirm: 'Are you sure?' } %>
      <button class="btn btn-mini cancel" type="button">Cancel</button>
      <button class="btn-primary btn btn-mini task-save" type="button">Save</button>
    </div>
  <% end %>
  <div class="content">
    <div class="actions pull-right">
      <% unless task.complete? %>
        <i class="icon-pencil"></i>
      <% end %>
      <i class="icon-move"></i>
    </div>
    <span><%= task.description %></span>
    <div class="notes">
      <hr>
      <div><%= task.notes %></div>
    </div>
  </div>
</li>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>List</th>
    <th>Description</th>
    <th>Notes</th>
    <th>Complete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.list_id %></td>
    <td><%= task.description %></td>
    <td><%= task.notes %></td>
    <td><%= task.complete %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= @task.list_id %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Notes:</b>
  <%= @task.notes %>
</p>

<p>
  <b>Complete:</b>
  <%= @task.complete %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>